default_language_version:
  python: python3.11
fail_fast: false
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.3
    hooks:
      - id: pylint
        args: [
          "-rn",
          "-sn",
          "--disable=all",
          "--enable=W0611",
        ]
